name: build and piblish mtl-screenshot-api
on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t mtl-screenshot-api -f apps/mtl-screenshot-api/Dockerfile .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: docker tag mtl-screenshot-api registry.digitalocean.com/mtl-container-registry/mtl-screenshot-api
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/mtl-container-registry/mtl-screenshot-api
      - name: Deploy mtl-screenshot-app
        run: doctl apps create-deployment 82a3692d-babb-4e71-9ce3-33b516a9c707
